apiVersion: ar.dev/v1alpha1
kind: Agent
metadata:
  name: myagent
spec:
  source:
    image: localhost:5001/myagent:latest
    repository:
      url: https://github.com/solo-io/doc-examples
      subfolder: agentregistry/myagent
  modelProvider: bedrock
  modelName: us.anthropic.claude-sonnet-4-6
  description: myagent agent
  mcpServers:
    - kind: MCPServer
      name: mymcp
