apiVersion: ar.dev/v1alpha1
kind: MCPServer
metadata:
  name: mymcp
spec:
  description: mymcp MCP server
  source:
    package:
      launch:
        args:
        - type: positional
          value: src/main.py
        - type: positional
          value: --transport
        - type: positional
          value: http
        - type: positional
          value: --host
        - type: positional
          value: 0.0.0.0
        - type: positional
          value: --port
        - type: positional
          value: "3000"
        command: python3
      origin:
        identifier: localhost:5001/mymcp:latest
        oci:
          serverName: mymcp
        type: oci
      transport:
        path: /mcp
        port: 3000
        type: http
    repository:
      url: https://github.com/solo-io/doc-examples
      subfolder: agentregistry/mymcp
  title: mymcp
