apiVersion: ar.dev/v1alpha1
kind: MCPServer
metadata:
  name: myorg/mymcp
spec:
  description: mymcp MCP server
  source:
    package:
      identifier: localhost:5001/mymcp:latest
      registryType: oci
      transport:
        type: stdio
  title: mymcp
