apiVersion: ar.dev/v1alpha1
kind: Skill
metadata:
  name: myskill
spec:
  title: echo
  description: A simple skill that echoes a message back to the user.
  source:
    repository:
      url: https://github.com/solo-io/doc-examples
      branch: main
      subfolder: agentregistry/myskill
