apiVersion: ar.dev/v1alpha1
kind: Agent
metadata:
  name: myagent
spec:
  description: myagent agent
  modelName: gemini-2.5-flash
  modelProvider: gemini
  source:
    image: localhost:5001/myagent:latest
